name: hive_flutter
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 0.3.0+2
homepage: https://github.com/leisim/hive

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  path_provider: ^2.1.3
  path: 1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ">=1.8.0 <2.0.0"